### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by sixtyfive** [janlelis/unicode-sequence_name#1]
```
main » require "unicode/sequence_name"
=> true
main » Unicode::SequenceName.of 'ﺍ'
=> nil
main » Unicode::SequenceName.of "‼︎"
=> "DOUBLE EXCLAMATION MARK (text style)"
main » Unicode::SequenceName.of "a"
=> nil
main » Unicode::SequenceName.of "X"
=> nil
main » Unicode::SequenceName.of "நி"
=> "TAMIL SYLLABLE NI"
main » Unicode::SequenceName.of "م"
=> nil
```

Curiously enough the `uniscribe` tool works quite well with all of these.

**Comment by janlelis** [comment]
Hey @sixtyfive, I have to admit, it is confusing which gem is responsible for which Unicode descriptions. The *unicode-sequence_name gem* only covers characters which are constructed from multiple code points, while the [unicode-name gem](https://github.com/janlelis/unicode-name) has the list of single-code point names (uniscribe detects if the character is made from multiple codepoints to decide which one to use)

I am interested in providing a unified interface in some way, but I am not sure yet, how this should look like…

**Comment by sixtyfive** [comment]
> I am interested in providing a unified interface in some way, but I am not sure yet, how this should look like…

Now that you explained it to me I'm not even sure if there is a need for any change to the code. If that info had just been more prominently displayed somewhere (with links from one to the other and vice versa) I think that would have been fine.
